import type {
  FundingCategory,
  FundingProgramNature,
} from "@/engine/funding/schema";

export interface FundingOpportunityTemplate {
  id: string;
  opportunityName: string;
  type: FundingCategory;
  programNature: FundingProgramNature;
  source: string;
  url: string;
  eligibilityTags: string[];
  amountRange: string;
  documentsNeeded: string[];
  riskNotes: string[];
}

const SBA_FUNDING_GUIDE =
  "https://www.sba.gov/business-guide/plan-your-business/fund-your-business";
const SBA_LENDER_MATCH =
  "https://www.sba.gov/funding-programs/loans/lender-match-connects-you-lenders";

export const fundingOpportunityTemplates: FundingOpportunityTemplate[] = [
  template(
    "sba-7a",
    "SBA 7(a) loan pathway",
    "sba_7a",
    "loan",
    "U.S. Small Business Administration",
    "https://www.sba.gov/funding-programs/loans/7a-loans",
    ["small_business", "working_capital", "equipment", "lender_underwriting"],
    "Up to $5 million; confirm current terms and fit with a participating lender.",
    ["Business plan", "Use-of-funds schedule", "Financial projections", "Owner financial information"],
    ["SBA does not lend directly for ordinary 7(a) requests; the lender decides whether to approve the loan.", "Debt repayment must fit realistic cash flow."],
  ),
  template(
    "sba-504",
    "SBA 504 fixed-asset loan pathway",
    "sba_504",
    "loan",
    "U.S. Small Business Administration",
    "https://www.sba.gov/504",
    ["small_business", "major_fixed_assets", "equipment", "facility"],
    "Generally up to $5 million, with certain projects eligible for up to $5.5 million; verify current rules.",
    ["Business plan", "Fixed-asset quotes", "Financial projections", "Owner contribution evidence"],
    ["504 financing is intended for eligible major fixed assets and is not a general working-capital or inventory solution.", "Certified Development Company and lender underwriting still apply."],
  ),
  template(
    "sba-microloan",
    "SBA Microloan intermediary pathway",
    "sba_microloan",
    "loan",
    "U.S. Small Business Administration",
    "https://www.sba.gov/microloans",
    ["small_business", "microenterprise", "smaller_request", "intermediary_lender"],
    "Up to $50,000; verify intermediary requirements.",
    ["Use-of-funds schedule", "Startup cost estimate", "Cash-flow projection", "Owner background"],
    ["Each intermediary sets lending and credit requirements.", "Collateral and a personal guarantee may be requested."],
  ),
  template(
    "sba-lender-match",
    "SBA Lender Match",
    "sba_lender_match",
    "lender_referral",
    "U.S. Small Business Administration",
    SBA_LENDER_MATCH,
    ["small_business", "lender_discovery", "compare_terms"],
    "Varies by participating lender.",
    ["Business plan", "Requested amount", "Use-of-funds schedule", "Financial projections"],
    ["Lender Match is a referral tool, not a loan application or approval.", "Compare rates, fees, terms, and lender reputation."],
  ),
  template(
    "cdfi-loan",
    "CDFI loan research pathway",
    "cdfi_loan",
    "loan",
    "Community Development Financial Institutions Fund",
    "https://www.cdfifund.gov/programs-training/certification/cdfi",
    ["underserved_market", "mission_driven_lender", "local_lender_research"],
    "Varies by certified CDFI and loan product.",
    ["Business plan", "Use-of-funds schedule", "Financial projections", "Owner background"],
    ["CDFI products, service areas, and underwriting standards vary.", "Use the official Certified CDFI list and verify the institution before sharing financial information."],
  ),
  template(
    "community-bank",
    "Local community-bank loan research",
    "local_community_bank",
    "loan",
    "U.S. Small Business Administration funding guide",
    SBA_FUNDING_GUIDE,
    ["local_lender", "relationship_banking", "compare_terms"],
    "Varies by bank and underwriting.",
    ["Business plan", "Financial projections", "Owner financial information", "Use-of-funds schedule"],
    ["Approval, pricing, collateral, and guarantees vary by bank.", "Compare multiple written offers and avoid pressure tactics."],
  ),
  template(
    "credit-union",
    "Credit-union business loan research",
    "credit_union",
    "loan",
    "U.S. Small Business Administration funding guide",
    SBA_FUNDING_GUIDE,
    ["local_lender", "member_eligibility", "compare_terms"],
    "Varies by credit union and underwriting.",
    ["Business plan", "Financial projections", "Owner financial information", "Membership eligibility"],
    ["Business products and membership rules vary by credit union.", "Compare repayment terms, fees, and guarantees."],
  ),
  template(
    "state-grant",
    "State grant and incentive search",
    "state_grant",
    "grant_search",
    "State economic-development agency template",
    "https://www.sba.gov/local-assistance",
    ["state_specific", "live_connector_needed", "competitive"],
    "Varies by current state program.",
    ["Project summary", "Use-of-funds schedule", "State eligibility evidence", "Application-specific documents"],
    ["This is a search template, not a live state grant.", "Programs, deadlines, industries, and eligible uses change."],
  ),
  template(
    "local-incentive",
    "Local economic-development incentive search",
    "local_economic_development_incentive",
    "incentive_search",
    "Local economic-development resource template",
    "https://www.sba.gov/local-assistance",
    ["local_specific", "job_creation", "location_specific", "live_connector_needed"],
    "Varies by city, county, utility, and economic-development organization.",
    ["Project summary", "Location plan", "Job-creation estimate", "Use-of-funds schedule"],
    ["This is a research path, not a promised incentive.", "Local incentives may have location, job, investment, or timing requirements."],
  ),
  template(
    "grants-gov",
    "Grants.gov opportunity search",
    "grants_gov",
    "grant_search",
    "Grants.gov",
    "https://www.grants.gov/",
    ["federal_grant_search", "competitive", "live_search_needed"],
    "Varies by posted federal opportunity.",
    ["Entity registration if required", "Opportunity-specific application", "Project narrative", "Budget"],
    ["General startup grants are uncommon; only pursue posted opportunities that clearly fit.", "Deadlines and eligibility must be checked on the live opportunity notice."],
  ),
  template(
    "sam-gov",
    "SAM.gov federal contracting pathway",
    "sam_gov_contracting_pathway",
    "contracting_pathway",
    "SAM.gov",
    "https://sam.gov/entity-information",
    ["federal_contracting", "entity_registration", "uei"],
    "Contract value varies by posted opportunity; this is not a grant or loan.",
    ["Entity records", "Taxpayer information", "Banking information for registration", "Capability statement"],
    ["SAM.gov registration does not guarantee an award.", "Federal contracting requires fit, compliance, and active opportunity research."],
  ),
  template(
    "sbir-sttr",
    "SBIR/STTR research-award pathway",
    "sbir_sttr",
    "research_award",
    "SBIR.gov - America's Seed Fund",
    "https://www.sbir.gov/",
    ["technology", "research_and_development", "commercialization", "competitive_award"],
    "Varies by agency solicitation and phase.",
    ["Technical concept", "R&D work plan", "Commercialization plan", "Solicitation-specific application"],
    ["Awards are competitive and tied to federal R&D topics.", "A software label alone does not establish SBIR/STTR fit."],
  ),
  template(
    "veteran-program",
    "Veteran-owned business program research",
    "veteran_owned_program",
    "contracting_pathway",
    "U.S. Small Business Administration",
    "https://www.sba.gov/federal-contracting/contracting-assistance-programs/service-disabled-veteran-owned-small-businesses-program",
    ["veteran_owned", "certification_research", "federal_contracting"],
    "Program-dependent; verify current certification and opportunity details.",
    ["Ownership and control records", "Entity records", "Capability statement", "Program-specific application"],
    ["Veteran ownership selection does not by itself establish eligibility.", "Some pathways are contracting certifications or assistance programs rather than direct funding."],
  ),
  template(
    "disabled-veteran-program",
    "Service-disabled veteran-owned program research",
    "disabled_veteran_owned_program",
    "contracting_pathway",
    "U.S. Small Business Administration",
    "https://www.sba.gov/federal-contracting/contracting-assistance-programs/service-disabled-veteran-owned-small-businesses-program",
    ["service_disabled_veteran_owned", "vetcert", "federal_contracting"],
    "Program-dependent; verify current VetCert and opportunity details.",
    ["Ownership and control records", "Service-disabled veteran documentation", "Entity records", "Capability statement"],
    ["Self-identification is not certification.", "Contracting set-asides are opportunities to compete, not guaranteed awards."],
  ),
  template(
    "woman-owned-program",
    "Woman-owned business program research",
    "woman_owned_program",
    "contracting_pathway",
    "U.S. Small Business Administration",
    "https://www.sba.gov/federal-contracting/contracting-assistance-programs/women-owned-small-business-federal-contract-program",
    ["woman_owned", "wosb", "certification_research", "federal_contracting"],
    "Program-dependent; verify current certification and opportunity details.",
    ["Ownership and control records", "Entity records", "Capability statement", "Program-specific application"],
    ["Woman-owned status does not guarantee certification, funding, or an award.", "Some benefits are tied to eligible industries and contracting opportunities."],
  ),
  template(
    "minority-owned-program",
    "Minority-owned and underserved-business resource research",
    "minority_owned_program",
    "contracting_pathway",
    "U.S. Small Business Administration",
    "https://www.sba.gov/business-guide/grow-your-business/minority-owned-businesses",
    ["minority_owned", "underserved_market", "certification_research"],
    "Program-dependent; verify the exact program and current criteria.",
    ["Ownership and control records", "Entity records", "Business history", "Program-specific application"],
    ["Self-identification does not establish eligibility for any specific program.", "Certification and economic-disadvantage rules must be verified on the official program page."],
  ),
  template(
    "rural-program",
    "USDA Rural Development business-program research",
    "rural_program",
    "incentive_search",
    "USDA Rural Development",
    "https://www.rd.usda.gov/programs-services/business-programs",
    ["rural", "usda", "location_specific", "live_search_needed"],
    "Varies by USDA Rural Development program and intermediary.",
    ["Rural location evidence", "Project summary", "Use-of-funds schedule", "Program-specific application"],
    ["Rural ownership selection does not establish geographic or program eligibility.", "Many programs operate through lenders, public entities, nonprofits, or other intermediaries."],
  ),
  template(
    "tribal-program",
    "Indian Loan Guarantee and Insurance Program research",
    "tribal_program",
    "loan",
    "U.S. Department of the Interior - Indian Affairs",
    "https://www.bia.gov/service/loans/ilgp",
    ["tribal", "american_indian_alaska_native", "lender_guarantee"],
    "Individuals may seek guarantees up to $500,000; other entity limits vary and must be verified.",
    ["Eligibility records", "Lender documentation", "Business plan", "Financial projections"],
    ["The program reduces lender risk; it is not a guaranteed loan approval.", "Verify applicant and lender requirements with Indian Affairs."],
  ),
  template(
    "crowdfunding",
    "Crowdfunding research pathway",
    "crowdfunding",
    "community_funding",
    "U.S. Small Business Administration funding guide",
    SBA_FUNDING_GUIDE,
    ["community_support", "campaign", "platform_terms"],
    "Varies by campaign type, platform, and applicable rules.",
    ["Campaign plan", "Offer or reward details", "Marketing plan", "Platform terms review"],
    ["Platform terms, fees, fulfillment obligations, and securities rules can apply.", "Do not assume campaign demand or funding success."],
  ),
  template(
    "equipment-financing",
    "Equipment-financing research",
    "equipment_financing",
    "loan",
    "U.S. Small Business Administration funding guide",
    SBA_FUNDING_GUIDE,
    ["equipment", "asset_backed", "compare_terms"],
    "Varies by equipment value, lender, lease, and financing structure.",
    ["Equipment quotes", "Use-of-funds schedule", "Financial projections", "Vendor terms"],
    ["Total cost, liens, down payment, warranties, and early-payoff terms require review.", "Financing equipment before validating demand can create avoidable fixed obligations."],
  ),
  template(
    "bootstrapping",
    "Staged bootstrapping path",
    "bootstrapping",
    "self_funding",
    "U.S. Small Business Administration funding guide",
    SBA_FUNDING_GUIDE,
    ["owner_capital", "staged_spending", "validation_first"],
    "Limited to capital the founder can afford to risk.",
    ["Personal risk limit", "Staged spending plan", "Validation milestones", "Cash reserve target"],
    ["The founder bears the financial risk.", "Do not jeopardize essential savings or retirement security."],
  ),
  template(
    "friends-family",
    "Friends-and-family funding research",
    "friends_family",
    "self_funding",
    "U.S. Small Business Administration funding guide",
    SBA_FUNDING_GUIDE,
    ["personal_network", "document_terms", "relationship_risk"],
    "Varies by contributor and documented agreement.",
    ["Written terms", "Repayment or ownership structure", "Risk disclosure", "Professional review"],
    ["Informal arrangements can damage relationships and create legal or tax issues.", "Document terms and obtain appropriate professional advice."],
  ),
  template(
    "angel-investment",
    "Angel-investment research",
    "angel_investment",
    "equity",
    "U.S. Small Business Administration funding guide",
    SBA_FUNDING_GUIDE,
    ["high_growth", "equity", "investor_due_diligence"],
    "Varies by investor, traction, valuation, and round.",
    ["Pitch summary", "Business plan", "Financial model", "Traction evidence", "Entity and ownership records"],
    ["Investment can dilute ownership and add governance obligations.", "A scalable growth case and investor fit are required."],
  ),
  template(
    "venture-capital",
    "Venture-capital research",
    "venture_capital",
    "equity",
    "U.S. Small Business Administration funding guide",
    SBA_FUNDING_GUIDE,
    ["scalable_high_growth", "equity", "investor_due_diligence"],
    "Varies by fund, traction, valuation, and round.",
    ["Pitch deck", "Scalable growth model", "Financial model", "Traction evidence", "Entity and ownership records"],
    ["Venture capital is generally intended for high-growth businesses and usually exchanges capital for ownership and influence.", "Most ordinary local small businesses do not fit venture economics."],
  ),
];

function template(
  id: string,
  opportunityName: string,
  type: FundingCategory,
  programNature: FundingProgramNature,
  source: string,
  url: string,
  eligibilityTags: string[],
  amountRange: string,
  documentsNeeded: string[],
  riskNotes: string[],
): FundingOpportunityTemplate {
  return {
    id,
    opportunityName,
    type,
    programNature,
    source,
    url,
    eligibilityTags,
    amountRange,
    documentsNeeded,
    riskNotes,
  };
}
