import { engineResultSchema, type EngineResult } from "@/engine/shared/engine-result";
import type { SourceReference } from "@/engine/shared/source-reference";
import {
  CompetitorAnalysisInputSchema,
  CompetitorAnalysisSchema,
  type CompetitorAnalysis,
  type CompetitorAnalysisInput,
  type CompetitorRecord,
  type CompetitorRelationship,
  type ManualCompetitorRecord,
} from "@/engine/competitor-analysis/schema";

const intakeSource: SourceReference = {
  id: "competitor-analysis-intake",
  title: "Founder-entered competitor names",
  sourceName: "VentureForge intake",
  sourceType: "user",
  notes: "Competitor names and classifications require independent research.",
};

const manualSource: SourceReference = {
  id: "competitor-analysis-manual-records",
  title: "Founder-entered competitor research",
  sourceName: "VentureForge manual competitor records",
  sourceType: "manual",
  notes: "Manual competitor notes have not been independently verified.",
};

export const CompetitorAnalysisEngine = {
  analyze(inputDraft: CompetitorAnalysisInput): EngineResult<CompetitorAnalysis> {
    const input = CompetitorAnalysisInputSchema.parse(inputDraft);
    const records = mergeRecords([
      ...input.knownCompetitors.map((name) => recordFromKnownName(name, input)),
      ...input.manualCompetitorRecords.map(recordFromManual),
    ]);
    const directCompetitors = records.filter(
      (record) => record.directOrIndirect === "direct",
    );
    const indirectCompetitors = records.filter(
      (record) => record.directOrIndirect === "indirect",
    );
    const substituteProductsOrServices = unique([
      ...records
        .filter((record) => record.directOrIndirect === "substitute")
        .map((record) => record.name),
      "Delay, do-it-yourself, in-house, or no-purchase alternatives",
    ]);
    const missingInformation = buildMissingInformation(input, records);
    const warnings = buildWarnings(input);
    const nextActions = buildNextActions(input, records);
    const sources = input.manualCompetitorRecords.length > 0
      ? [intakeSource, manualSource]
      : [intakeSource];

    const analysis = CompetitorAnalysisSchema.parse({
      directCompetitors,
      indirectCompetitors,
      substituteProductsOrServices,
      competitiveGrid: records.map((record) => ({
        competitorName: record.name,
        relationship: record.directOrIndirect,
        pricePosition: record.pricePosition,
        strengths: record.perceivedStrengths,
        weaknesses: record.perceivedWeaknesses,
        differentiators: record.differentiators,
        threatLevel: record.threatLevel,
        evidenceLabel: record.evidenceLabel,
      })),
      barriersToEntry: [
        "Customer trust, switching behavior, and incumbent visibility may slow adoption.",
        "Pricing, channel access, operating capability, and regulatory requirements need local research.",
        input.industry
          ? `Industry-specific barriers for ${input.industry} have not been verified.`
          : "The industry is missing, so industry-specific barriers cannot be assessed.",
      ],
      likelyCompetitorResponse: [
        "Estimated response: established alternatives may emphasize trust, convenience, price, or existing relationships.",
        "Estimated response: direct competitors may copy visible promotions or strengthen retention efforts.",
        "Validate likely responses through observed marketing, pricing, and customer interviews.",
      ],
      whiteSpaceOpportunities: [
        `Estimated opportunity: solve the stated need more clearly for ${input.targetCustomer || "a defined customer segment"}.`,
        "Estimated opportunity: reduce friction in discovery, purchase, fulfillment, or follow-up.",
        "Validate white-space hypotheses against direct competitors, indirect alternatives, and customer behavior.",
      ],
      differentiationRecommendations: [
        "Choose one customer problem and make the benefit easier to understand than competing alternatives.",
        "Test whether convenience, trust, specialization, speed, service, or pricing creates a meaningful advantage.",
        "Avoid unsupported claims about competitor quality, reviews, or market share.",
      ],
    });

    return engineResultSchema(CompetitorAnalysisSchema).parse({
      data: analysis,
      confidence: calculateConfidence(input, records),
      assumptions: [
        "Founder-entered competitor names are treated as candidates until researched.",
        "Unverified competitor attributes are labeled estimated or not yet researched.",
        "No exact review score or market-share claim is generated by this engine.",
      ],
      missingInformation,
      warnings,
      sources,
      nextActions,
    });
  },
};

function recordFromKnownName(
  name: string,
  input: CompetitorAnalysisInput,
): CompetitorRecord {
  const relationship = classifyKnownCompetitor(name);
  return {
    name,
    location: describeLocation(input),
    directOrIndirect: relationship,
    productsServices: ["Not yet researched."],
    pricePosition: input.pricingIdea
      ? `Not yet researched. Compare against founder pricing idea: ${input.pricingIdea}.`
      : "Not yet researched.",
    targetCustomer: input.targetCustomer || "Not yet researched.",
    perceivedStrengths: ["Not yet researched."],
    perceivedWeaknesses: ["Not yet researched."],
    reviewsSummary: "No verified review summary recorded.",
    differentiators: ["Not yet researched."],
    marketingChannels: ["Not yet researched."],
    estimatedMarketPosition: "Estimated only: market position has not been researched.",
    threatLevel: "unknown",
    evidenceLabel: "user_provided",
  };
}

function recordFromManual(record: ManualCompetitorRecord): CompetitorRecord {
  return {
    ...record,
    location: record.location || "Location not yet recorded.",
    productsServices: withFallback(record.productsServices),
    pricePosition: record.pricePosition || "Not yet researched.",
    targetCustomer: record.targetCustomer || "Not yet researched.",
    perceivedStrengths: withFallback(record.perceivedStrengths),
    perceivedWeaknesses: withFallback(record.perceivedWeaknesses),
    reviewsSummary: record.reviewsSummary ||
      "No verified review summary recorded.",
    differentiators: withFallback(record.differentiators),
    marketingChannels: withFallback(record.marketingChannels),
    estimatedMarketPosition: record.estimatedMarketPosition ||
      "Estimated only: market position has not been researched.",
    evidenceLabel: "manual",
  };
}

function classifyKnownCompetitor(name: string): CompetitorRelationship {
  const text = name.toLowerCase();
  if (
    ["streaming", "do-it-yourself", "diy", "in-house", "informal", "automated"]
      .some((keyword) => text.includes(keyword))
  ) {
    return "substitute";
  }
  if (
    ["online", "marketplace", "delivery app", "fast-casual", "national"]
      .some((keyword) => text.includes(keyword))
  ) {
    return "indirect";
  }
  return "direct";
}

function mergeRecords(records: CompetitorRecord[]): CompetitorRecord[] {
  const byName = new Map<string, CompetitorRecord>();
  for (const record of records) {
    const key = record.name.toLowerCase();
    const existing = byName.get(key);
    if (!existing || record.evidenceLabel === "manual") {
      byName.set(key, record);
    }
  }
  return [...byName.values()];
}

function buildMissingInformation(
  input: CompetitorAnalysisInput,
  records: CompetitorRecord[],
): string[] {
  return unique([
    records.length === 0 ? "No competitors have been identified." : undefined,
    !input.industry ? "The industry is missing." : undefined,
    !input.targetCustomer ? "The target customer is missing." : undefined,
    !input.pricingIdea ? "The founder pricing idea is missing." : undefined,
    "Verified competitor products, services, and pricing are incomplete.",
    "Verified competitor strengths, weaknesses, and marketing channels are incomplete.",
    "Exact market-share data is unavailable unless a sourced record is added.",
  ]);
}

function buildWarnings(input: CompetitorAnalysisInput): string[] {
  return unique([
    "Competitor classifications are founder-provided, manual, or estimated. Verify them before relying on the analysis.",
    "The engine does not invent exact review scores or exact market-share claims.",
    input.manualCompetitorRecords.length === 0
      ? "No enriched manual competitor records are available yet."
      : undefined,
  ]);
}

function buildNextActions(
  input: CompetitorAnalysisInput,
  records: CompetitorRecord[],
): string[] {
  return unique([
    records.length === 0
      ? "Research and record direct competitors, indirect alternatives, and substitutes."
      : "Verify each recorded competitor's offer, pricing, channels, and customer segment.",
    "Collect sourced competitor pricing without scraping sites in ways that violate their terms.",
    "Interview customers about the alternatives they use today and why.",
    input.manualCompetitorRecords.length === 0
      ? "Add manual competitor records with source notes."
      : undefined,
  ]);
}

function calculateConfidence(
  input: CompetitorAnalysisInput,
  records: CompetitorRecord[],
): number {
  let score = 15;
  if (records.length > 0) score += 20;
  if (records.length >= 3) score += 10;
  if (input.manualCompetitorRecords.length > 0) score += 20;
  if (input.location.city && input.location.stateCode) score += 10;
  if (input.industry) score += 10;
  if (input.targetCustomer) score += 10;
  if (input.pricingIdea) score += 5;
  return clamp(score);
}

function describeLocation(input: CompetitorAnalysisInput): string {
  return [
    input.location.city,
    input.location.county,
    input.location.stateCode,
    input.location.zipCode,
  ].filter(Boolean).join(", ") || "Location not yet recorded.";
}

function withFallback(values: string[]): string[] {
  return values.length > 0 ? values : ["Not yet researched."];
}

function unique(values: (string | undefined)[]): string[] {
  return [...new Set(values.filter((value): value is string => value !== undefined))];
}

function clamp(value: number): number {
  return Math.max(0, Math.min(100, Math.round(value)));
}
